---
setup_required:
  children:
    home_network_mac_ip_reservations:
    portable_network_mac_ip_reservations:

home_network_mac_ip_reservations:
  hosts:
    192.168.0.220:
    192.168.0.221:
    192.168.0.222:
    192.168.0.223:
    192.168.0.224:
    192.168.0.225:

portable_network_mac_ip_reservations:
  hosts:
    192.168.8.220:
    192.168.8.113:
    192.168.8.221:
    192.168.8.222:
    192.168.8.223:
    192.168.8.224:
    192.168.8.225:

initialized_hosts:
  children:
    k8s_masters:
    k8s_workers:

pi_user:
  children:
    setup_required:

ssh_key:
  children:
    k8s_masters:
    k8s_workers:

k8s_masters:
  hosts:
    192.168.0.[200:200]:
    192.168.8.[200:200]:

k8s_workers:
  hosts:
    192.168.0.[201:205]:
    192.168.8.[201:205]:
