---
ungrouped:
  hosts:
    localhost:
  vars:
    ansible_connection: local

setup-required:
  hosts:
    192.168.0.188:
      last_octet: 200
      desired_hostname: k8s-master-1
    192.168.0.111:
      last_octet: 201
      desired_hostname: k8s-worker-1
    192.168.0.170:
      last_octet: 202
      desired_hostname: k8s-worker-2
    192.168.0.109:
      last_octet: 203
      desired_hostname: k8s-worker-3
    192.168.0.123:
      last_octet: 204
      desired_hostname: k8s-worker-4
    192.168.0.114:
      last_octet: 205
      desired_hostname: k8s-worker-5
  vars:
    ansible_user: pi
    first_3_octets: 192.168.0

initialized-hosts:
  hosts:
    192.168.0.[200:205]:
  vars:
    ansible_user: pi

k8s-masters:
  hosts:
    192.168.0.[200:200]:
  vars:
    ansible_user: pi

k8s-workers:
  hosts:
    192.168.0.[201:205]:
  vars:
    ansible_user: pi
