---
fresh_master_1_pis:
  hosts:
    192.168.0.220:
    192.168.8.220:

fresh_worker_1_pis:
  hosts:
    192.168.0.221:
    192.168.8.221:
    192.168.8.113:

fresh_worker_2_pis:
  hosts:
    192.168.0.222:
    192.168.8.222:

fresh_worker_3_pis:
  hosts:
    192.168.0.223:
    192.168.8.223:

fresh_worker_4_pis:
  hosts:
    192.168.0.224:
    192.168.8.224:

fresh_worker_5_pis:
  hosts:
    192.168.0.225:
    192.168.8.225:

k8s_masters:
  hosts:
    192.168.0.[200:200]:
    192.168.8.[200:200]:

k8s_workers:
  hosts:
    192.168.0.[201:205]:
    192.168.8.[201:205]:

setup_required:
  children:
    fresh_master_1_pis:
    fresh_worker_1_pis:
    fresh_worker_2_pis:
    fresh_worker_3_pis:
    fresh_worker_4_pis:
    fresh_worker_5_pis:

initialized_hosts:
  children:
    k8s_masters:
    k8s_workers:

pi_user:
  children:
    setup_required:

ssh_user:
  children:
    k8s_masters:
    k8s_workers:
