---
setup-required:
  children:
    home_network:
    portable_network:

home_network:
  hosts:
    192.168.0.200:
      desired_hostname: k8s-master-1
      last_octet: 200
    192.168.0.201:
      desired_hostname: k8s-worker-1
      last_octet: 201
    192.168.0.202:
      desired_hostname: k8s-worker-2
      last_octet: 202
    192.168.0.203:
      desired_hostname: k8s-worker-3
      last_octet: 203
    192.168.0.204:
      desired_hostname: k8s-worker-4
      last_octet: 204
    192.168.0.205:
      desired_hostname: k8s-worker-5
      last_octet: 205
  vars:
    first_3_octets: 192.168.0

portable_network:
  hosts:
    192.168.8.220:
      desired_hostname: k8s-master-1
      last_octet: 200
    192.168.8.113:
      desired_hostname: k8s-worker-1
      last_octet: 201
    192.168.8.221:
      desired_hostname: k8s-worker-1
      last_octet: 201
    192.168.8.222:
      desired_hostname: k8s-worker-2
      last_octet: 202
    192.168.8.223:
      desired_hostname: k8s-worker-3
      last_octet: 203
    192.168.8.224:
      desired_hostname: k8s-worker-4
      last_octet: 204
    192.168.8.225:
      desired_hostname: k8s-worker-5
      last_octet: 205
  vars:
    first_3_octets: 192.168.8

initialized-hosts:
  children:
    k8s-masters:
    k8s-workers:

pi-user:
  children:
    setup-required:
  vars:
    ansible_user: pi
    ansible_connection: paramiko
ssh-key:
  children:
    k8s-masters:
    k8s-workers:
  vars:
    ansible_user: pi
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

k8s-masters:
  hosts:
    192.168.0.[200:200]:
    192.168.8.[200:200]:


k8s-workers:
  hosts:
    192.168.0.[201:205]:
    192.168.8.[201:205]:
