---
- name: Initial setup of raspberry pi
  hosts: all

  vars_prompt:
    - name: network_ssid
      prompt: "What is the wifi network name (SSID)?"
      private: false
    - name: network_psk
      prompt: "What is the wifi network password (PSK)?"

  vars:
    desired_keyboard_layout: "en"
    setup_static_ip_eth0: false
    setup_static_ip_wlan0: false

  tasks:
    - import_tasks: ../tasks/set-timezone.yml
      vars:
        desired_timezone: US/Eastern
    - import_tasks: ../tasks/set-locales.yml
      vars:
        desired_locale: en_US
        desired_encoding: UTF-8
        desired_language: en
    - import_tasks: ../tasks/disable-swap.yml
    - import_tasks: ../tasks/set-static-ip-eth0.yml
      when: setup_static_ip_eth0 == true
      vars:
        first_3_octets: "{{ first_3_octets }}"
        last_octet: "{{ last_octet }}"
    - import_tasks: ../tasks/set-static-ip-wlan0.yml
      when: setup_static_ip_wlan0 == true
      vars:
        first_3_octets: "{{ first_3_octets }}"
        last_octet: "{{ last_octet }}"
    - block:
        - import_tasks: ../tasks/set-wifi-country.yml
          vars:
            desired_iso_country: US
        - import_tasks: ../tasks/connect-to-wifi.yml
          vars:
            network_ssid: "{{ network_ssid }}"
            network_psk: "{{ network_psk }}"
      when: network_ssid is defined and network_psk is defined

    - import_tasks: ../tasks/configure-heartbeat.yml

    - import_tasks: ../tasks/resize-root-filesystem.yml
    - meta: flush_handlers

    - import_tasks: ../tasks/update-upgrade.yml

    - import_tasks: ../tasks/set-hostname.yml
    - meta: flush_handlers

    - import_tasks: ../tasks/add-ssh-authorized-key.yml
    - import_tasks: ../tasks/delete-pi-user-password.yml

  handlers:
    - import_tasks: ../handlers/reboot.yml
