---
- name: Initial setup of raspberry pis
  hosts: init-setup-required

  vars_prompt:
    - name: network_ssid
      prompt: "What is the wifi network name (SSID)?"
      private: no
    - name: network_psk
      prompt: "What is the wifi network password (PSK)?"

  vars:
    desired_timezone: "US/Eastern"
    # locale values can be found in /usr/share/i18n/SUPPORTED
    desired_iso_country: "US"
    desired_keyboard_layout: "en"
    desired_language: "en"
    desired_encoding: "UTF-8"
    desired_locale: "en_US"
    desired_locale_short: "{{ desired_locale.split()[0] }}"

  tasks:
    - name: Check if we need to resize FS
      stat:
        path: /etc/init.d/resize2fs_once
      register: file_created_by_expand_rootfs
    - name: Ensures root FS is resized
      become: true
      command: raspi-config --expand-rootfs
      notify:
        - reboot
      when: file_created_by_expand_rootfs.stat.exists == false

    - name: Sets the timezone
      timezone:
        name: "{{ desired_timezone }}"

    - name: Unsets default GB locale
      become: true
      replace:
        path: /etc/locale.gen
        regexp: "^en_GB.UTF-8 UTF-8"
        replace: "# en_GB.UTF-8 UTF-8"
    - name: Sets target locale to generate locale files from
      become: true
      replace:
        path: /etc/locale.gen
        regexp: '# {{ desired_locale }}.{{ desired_encoding }} {{ desired_encoding }}'
        replace: "{{ desired_locale }}"
      register: local_gen_config
    - name: Regenerates locale files
      become: true
      shell: dpkg-reconfigure -f noninteractive locales
      when: local_gen_config.changed
    - name: Sets the default locale
      become: true
      blockinfile:
        path: /etc/default/locale
        block: |
          LANG="{{ desired_locale }}.{{ desired_encoding }}"
          LANGUAGE="{{ desired_locale }}:{{ desired_language  }}"

    - name: Check if swap needs to be disabled
      become: true
      shell: swapon --summary
      register: swap_check
    - name: Disables swap
      become: true
      shell: "{{ item }}"
      with_items:
        - dphys-swapfile swapoff
        - dphys-swapfile uninstall
        - update-rc.d dphys-swapfile remove
        - apt purge dphys-swapfile
      notify: reboot
      when: swap_check.stdout != ""

    - name: Configures c group options
      become: true
      lineinfile:
        path: /boot/cmdline.txt
        regexp: cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory
        line: cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory
      notify: reboot

    - name: Update DHCPCD to assign static IP on eth0 and wan0
      become: true
      blockinfile:
        path: /etc/dhcpcd.conf
        block: |
          interface eth0
          static ip_address={{ first_3_octets }}.{{ last_octet }}/24
          static routers={{ first_3_octets  }}.1
          static domain_name_servers=8.8.8.8

          interface wlan0
          static ip_address={{ first_3_octets }}.{{ last_octet }}/24
          static routers={{ first_3_octets  }}.1
          static domain_name_servers=8.8.8.8
      notify: reboot

    - name: Update WPA config with ISO country code
      become: true
      lineinfile:
        path: /etc/wpa_supplicant/wpa_supplicant.conf
        regexp: '^country='
        line: "country={{ desired_iso_country }}"
    - name: Setup pi onto target network
      become: true
      blockinfile:
        path: /etc/wpa_supplicant/wpa_supplicant.conf
        block: |
          network={
            ssid="{{ network_ssid }}"
            psk="{{ network_psk }}"
          }

  handlers:
    - name: reboot
      shell: "sleep 1 && shutdown -r now +1"
      async: 1
      poll: 0
      notify:
        - wait for reboot
    - name: wait for reboot
      wait_for_connection:
        delay: 5
        timeout: 300

