---
- name: Initial setup of raspberry pi
  hosts: setup-required

  vars_prompt:
    - name: network_ssid
      prompt: "What is the wifi network name (SSID)?"
      private: false
    - name: network_psk
      prompt: "What is the wifi network password (PSK)?"

  vars:
    desired_keyboard_layout: "en"
    setup_static_ip_eth0: false
    setup_static_ip_wlan0: false

  tasks:
    - import_tasks: ../tasks/resize-root-filesystem.yml
    - import_tasks: ../tasks/set-hostname.yml
    - import_tasks: ../tasks/set-timezone.yml
      vars:
        desired_timezone: US/Eastern
    - import_tasks: ../tasks/set-locales.yml
      vars:
        desired_locale: en_US
        desired_encoding: UTF-8
        desired_language: en
    - import_tasks: ../tasks/disable-swap.yml
    - import_tasks: ../tasks/configure-c-groups.yml
    - import_tasks: ../tasks/set-static-ip-eth0.yml
      when: setup_static_ip_eth0 == true
      vars:
        first_3_octets: "{{ first_3_octets }}"
        last_octet: "{{ last_octet }}"
    - import_tasks: ../tasks/set-static-ip-wlan0.yml
      when: setup_static_ip_wlan0 == true
      vars:
        first_3_octets: "{{ first_3_octets }}"
        last_octet: "{{ last_octet }}"
    - import_tasks: ../tasks/set-wifi-country.yml
      vars:
        desired_iso_country: US
    - import_tasks: ../tasks/connect-to-wifi.yml
      vars:
        network_ssid: "{{ network_ssid }}"
        network_psk: "{{ network_psk }}"
    - import_tasks: ../tasks/configure-heartbeat.yml
    - import_tasks: ../tasks/rotate-lcd-screen.yml
    - import_tasks: ../tasks/add-ssh-authorized-key.yml
    - import_tasks: ../tasks/delete-pi-user-password.yml

  handlers:
    - name: reboot
      become: true
      shell: "sleep 1 && shutdown -r now +1"
      async: 1
      poll: 0
      notify:
        - wait for reboot
    - name: wait for reboot
      wait_for_connection:
        delay: 5
        timeout: 300
