---
- name: Initial setup of raspberry pis
  hosts: init-setup-required
  become: true
  roles:
    - role: mikolak-net.raspi_config
      raspi_config_update_packages: yes
      raspi_config_expanded_filesystem: yes
      raspi_config_locale: en_US.UTF-8
      raspi_config_timezone: US/Eastern
