---
- name: k3s setup
  hosts: k8s-masters

  tasks:
    - set_fact:
        k8s_pi_cluster_home: "~/.k8s-pi-cluster"
        host_ip_address: "{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}"
    - name: Check if we need to install k3s
      become: true
      stat:
        path: /var/lib/rancher/k3s/server/node-token
      register: out_node_token_file
    - name: Install k3s
      block:
        - name: Install k3s via shell method
          shell: curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
      when: out_node_token_file.stat.exists != true
    - name: Create k8s pi cluster in users home directory
      file:
        path: "{{ k8s_pi_cluster_home }}"
        state: directory
      delegate_to: localhost
    - name: Get the master(s) node token file
      become: true
      fetch:
        src: /var/lib/rancher/k3s/server/node-token
        dest: "{{ k8s_pi_cluster_home }}/{{ host_ip_address }}-node-token"
        mode: "0740"
        flat: true
    - name: Get the k8s kubeconfig file from master
      become: true
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ k8s_pi_cluster_home }}/{{ host_ip_address }}-kubeconfig.yml"
        mode: "0740"
        flat: true
    - name: Replace 127.0.0.1 with host IP
      replace:
        path: "{{ k8s_pi_cluster_home }}/{{ host_ip_address }}-kubeconfig.yml"
        regexp: "127.0.0.1"
        replace: "{{ host_ip_address }}"
      delegate_to: localhost

- name: Configure workers
  hosts: k8s-workers

  tasks:
    - set_fact:
        k3s_url: https://192.168.8.200:6443
        k8s_pi_cluster_home: "~/.k8s-pi-cluster"
    - set_fact:
        node_token_files:
          - "{{ k8s_pi_cluster_home }}/192.168.8.200-node-token"

    - name: Check if k3s needs to be installed
      stat:
        path: /usr/local/bin/k3s-uninstall.sh
      register: k3s_uninstall_script
    - name: Install k3s for workers
      block:
        - name: Create pi cluster home
          file:
            path: "{{ k8s_pi_cluster_home }}"
            state: directory
            mode: "0740"
        - name: Copy up node_token file(s)
          copy:
            src: "{{ item }}"
            dest: "{{ item }}"
            mode: "0740"
          with_items: "{{ node_token_files }}"
        # TODO: Check if k3s has already been installed on the node
        - name: Install k3s for workers
          shell: "curl -sfL https://get.k3s.io | K3S_URL={{ k3s_url }} K3S_TOKEN=\"$(cat /home/pi/.k8s-pi-cluster/192.168.8.200-node-token)\" sh -"
          async: 1000
          poll: 0
          register: k3s_worker_setup
        - name: Check on status
          async_status:
            jid: "{{ k3s_worker_setup.ansible_job_id }}"
          register: k3s_worker_setup_job_result
          until: k3s_worker_setup_job_result.finished
          retries: 60
      when: k3s_uninstall_script.stat.exists != true
