---
- name: Configure any touchscreens that are attached to any raspberry pis
  hosts: all

  tasks:
    - name: Detects if touchscreen is installed
      shell:
        cmd: dmesg | grep -i ft5406
      register: touchscreen_detect
      ignore_errors: true

    - name: touchscreen setup
      block:
        - import_tasks: ../tasks/rotate-lcd-screen.yml
        - import_tasks: ../tasks/setup-touchscreen.yml
        - import_tasks: ../tasks/configure-desktop-environment.yml
        - import_tasks: ../tasks/setup-virtual-keyboard.yml
        - import_tasks: ../tasks/desktop-autologin.yml
      when: touchscreen_detect.stdout != ""

  handlers:
    - import_tasks: ../handlers/reboot.yml
