---
- name: Setup SD Card with Rasbian and then create SSH file
  hosts: localhost

  vars_prompt:
  - name: image_file_location
    prompt: "Absolute path of desired image to flash SD card with"
    private: false

  tasks:
    - name: Check that provided OS image exists
      stat:
        path: "{{ image_file_location }}"
        get_attributes: false
        get_checksum: false
        get_mime: false
      register: image_file

    - fail:
        msg: "Provided image file '{{ image_file_location }}' does not exist! One cannot flash an OS onto an SD card without the OS image..!!"
      when: image_file.stat.exists != true

    - name: Finds attached SD card
      shell:
        cmd: "diskutil list external | head -n 1 | awk '{ print $1 }'"
      register: sd_card

    - name: Locates mounted disk
      shell:
        cmd: "df -lH | grep '/Volumes/*' | awk '{ print $9  }'"
      register: mounted_disk

    - name: Unmounts automatically mounted SD card (levelset)
      shell:
        cmd: "diskutil unmountdisk {{ sd_card.stdout }}"

    - name: Flashes SD card with Raspbian (1-3 minutes)
      become: true
      shell:
        cmd: "dd if={{ image_file_location }} of={{ sd_card.stdout | regex_replace('disk', 'rdisk') }} bs=1m"
      async: 1600
      poll: 10

    - name: Mounts the disk from flashed SD card
      shell:
        cmd: "diskutil mountDisk {{ sd_card.stdout }}"

    - name: Locates mounted disk
      shell:
        cmd: "df -lH | grep '/Volumes/*' | awk '{ print $9  }'"
      register: mounted_disk

    - name: Touches a "ssh" file
      file:
        path: "{{ mounted_disk.stdout }}/ssh"
        state: touch

    - name: Unmounts SD card
      shell:
        cmd: "diskutil unmountDisk {{ sd_card.stdout }}"

    - name: Notifies playbook user that SD card setup is complete
      say:
        msg: S D card setup completed. S D card unmounted. Enjoy!
        voice: Zarvox
