---
- name: Setup SD Card with Rasbian and then create SSH file
  hosts: localhost

  vars_prompt:
  - name: image_file_location
    prompt: "Absolute path of desired image to flash SD card with"
    private: no

  tasks:
    - name: Finds attached SD card
      shell:
        cmd: "diskutil list external | head -n 1 | awk '{ print $1 }'"
      register: sd_card

    - name: Locates mounted disk
      shell:
        cmd: "df -lH | grep '/Volumes/*' | awk '{ print $9  }'"
      register: mounted_disk

    - name: Checks for initial setup taint file
      stat:
        path: "{{ mounted_disk.stdout }}/new-car-smell"
      register: taint_file_check

    - name: Unmounts automatically mounted SD card (levelset)
      shell:
        cmd: "diskutil unmountdisk {{ sd_card.stdout }}"

    - name: Flashes SD card with Raspbian (takes a long time! ~5-10 minutes)
      become: true
      shell:
        cmd: "dd if={{ image_file_location }} of={{ sd_card.stdout | regex_replace('disk', 'rdisk') }} bs=1m"
      async: 1600
      poll: 10
      when: taint_file_check.stat.exists == false

    - name: Mounts the disk from flashed SD card
      shell:
        cmd: "diskutil mountDisk {{ sd_card.stdout }}"

    - name: Locates mounted disk
      shell:
        cmd: "df -lH | grep '/Volumes/*' | awk '{ print $9  }'"
      register: mounted_disk

    - name: Touches a "ssh" file
      file:
        path: "{{ mounted_disk.stdout }}/ssh"
        state: touch

    - name: Creates taint file
      file:
        path: "{{ mounted_disk.stdout  }}/new-car-smell"
        state: touch

    - name: Unmounts SD card
      shell:
        cmd: "diskutil unmountDisk {{ sd_card.stdout }}"

    - name: Notifies playbook user that SD card setup is complete
      say:
        msg: Setup of the S D card has been completed. S D card unmounted. Enjoy!
        voice: Zarvox

