---
- name: Update and upgrade all hosts
  hosts: all

  tasks:
    - name: Update
      become: true
      apt:
        update_cache: yes
    - name: Upgrade
      become: true
      apt:
        upgrade: dist
