---
- name: Setup pi onto target network
  become: true
  blockinfile:
    path: /etc/wpa_supplicant/wpa_supplicant.conf
    block: |
      network={
        ssid="{{ network_ssid }}"
        psk="{{ network_psk }}"
      }
