---
- name: Configure red onboard LED to display as a heartbeat
  become: true
  lineinfile:
    line: "{{ item }}"
    dest: /boot/config.txt
    regexp: "^{{ item }}"
  with_items:
    - dtparam=pwr_led_trigger=heartbeat
    - dtparam=act_led_trigger=mmc0
  notify:
    - reboot
