---
# TODO: Get this working ^^
# https://www.raspberrypi.org/documentation/linux/usage/cron.md
# maybe...
# @reboot sh /home/pi/make-red-led-a-heartbeat.sh
- name: Ensure /sys/class/leds/led0/trigger is attached to heartbeat
  lineinfile:
    path: /sys/class/leds/led0/trigger
    regexp: '\[heartbeat\]'
    state: absent
  check_mode: true
  changed_when: false
  register: onboard_red_led
