---
- name: Check if we need to resize FS
  stat:
    path: /etc/init.d/resize2fs_once
  register: created_file_from_expand_rootfs

- name: Resize root FS
  block:
    - name: Ensures root FS is resized
      become: true
      command: raspi-config --expand-rootfs
      notify:
        - reboot
    - name: Check if the file exists after raspi-config proc
      stat:
        path: /etc/init.d/resize2fs_once
    - meta: flush_handlers
  when: created_file_from_expand_rootfs.stat.exists != true
